import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useLucid } from '../context/LucidContext'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { connect, lockUtxoAlways, redeemUtxoAlways, lockUtxo, redeemUtxo } = useLucid()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://html5zombo.com/">Zombo.com!</a>
        </h1>

       <p>
       <br />
        <button onClick={connect}>Connect</button><br />
        <button onClick={() => {lockUtxoAlways(1_000_000)}}>Lock Always</button><br />
        <button onClick={redeemUtxoAlways}>Redeem Always</button><br />
        <button onClick={() => {lockUtxo(420, 6_900_000)}}>Lock Matching</button><br />
        <button onClick={() => {redeemUtxo(420)}}>Redeem 420</button><br />
        <button onClick={() => {redeemUtxo(69)}}>Redeem 69</button><br />
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
